mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.cat.little.model
server:
  port: 10085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 5
    max-wait: 10000
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://116.196.77.250:3306/shiro
    username: root
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp
#  security:
#    user:
#      name: user
#      password: user
