spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

server:
  servlet:
    context-path: /test
